export const ICMS_CST_OPTIONS = [
    { value: "00", label: "00 – Tributada integralmente" },
    { value: "10", label: "10 – Tributada e com cobrança do ICMS por ST" },
    { value: "20", label: "20 – Com redução de base de cálculo" },
    { value: "30", label: "30 – Isenta ou não tributada e com cobrança do ICMS por ST" },
    { value: "40", label: "40 – Isenta" },
    { value: "41", label: "41 – Não tributada" },
    { value: "50", label: "50 – Suspensão" },
    { value: "51", label: "51 – Diferimento" },
    { value: "60", label: "60 – ICMS cobrado anteriormente por ST" },
    { value: "70", label: "70 – Com redução de base e cobrança do ICMS por ST" },
    { value: "90", label: "90 – Outras" },
];

export const ICMS_CSOSN_OPTIONS = [
    { value: "101", label: "101 – Tributada pelo Simples com permissão de crédito" },
    { value: "102", label: "102 – Tributada pelo Simples sem permissão de crédito" },
    { value: "103", label: "103 – Isenção (faixa de receita bruta)" },
    { value: "201", label: "201 – Tributada pelo Simples com permissão de crédito e ST" },
    { value: "202", label: "202 – Tributada pelo Simples sem permissão de crédito e ST" },
    { value: "203", label: "203 – Isenção e ST (faixa de receita bruta)" },
    { value: "300", label: "300 – Imune" },
    { value: "400", label: "400 – Não tributada" },
    { value: "500", label: "500 – ICMS cobrado anteriormente por ST ou antecipação" },
    { value: "900", label: "900 – Outros" },
];

export const PIS_COFINS_CST_OPTIONS = [
    { value: "01", label: "01 – Operação tributável (alíquota básica)" },
    { value: "02", label: "02 – Operação tributável (alíquota diferenciada)" },
    { value: "03", label: "03 – Operação tributável (alíquota por unidade)" },
    { value: "04", label: "04 – Operação tributável (monofásica – revenda)" },
    { value: "05", label: "05 – Operação tributável (ST)" },
    { value: "06", label: "06 – Alíquota zero" },
    { value: "07", label: "07 – Isenta" },
    { value: "08", label: "08 – Sem incidência" },
    { value: "09", label: "09 – Suspensa" },
    { value: "49", label: "49 – Outras operações de saída" },
    { value: "50", label: "50 – Operação com direito a crédito" },
    { value: "51", label: "51 – Operação com direito a crédito (não tributada mercado interno)" },
    { value: "52", label: "52 – Operação com direito a crédito (exportação)" },
    { value: "53", label: "53 – Operação com direito a crédito (mista mercado interno)" },
    { value: "54", label: "54 – Operação com direito a crédito (mercado interno + exportação)" },
    { value: "55", label: "55 – Operação com direito a crédito (não tributada + exportação)" },
    { value: "56", label: "56 – Operação com direito a crédito (mista total)" },
    { value: "60", label: "60 – Crédito presumido" },
    { value: "98", label: "98 – Outras operações de entrada" },
    { value: "99", label: "99 – Outras operações" },
];

export const IPI_CST_OPTIONS = [
    { value: "00", label: "00 – Entrada com recuperação de crédito" },
    { value: "01", label: "01 – Entrada tributada com alíquota zero" },
    { value: "02", label: "02 – Entrada isenta" },
    { value: "03", label: "03 – Entrada não tributada" },
    { value: "04", label: "04 – Entrada imune" },
    { value: "05", label: "05 – Entrada com suspensão" },
    { value: "49", label: "49 – Outras entradas" },
    { value: "50", label: "50 – Saída tributada" },
    { value: "51", label: "51 – Saída tributada com alíquota zero" },
    { value: "52", label: "52 – Saída isenta" },
    { value: "53", label: "53 – Saída não tributada" },
    { value: "54", label: "54 – Saída imune" },
    { value: "55", label: "55 – Saída com suspensão" },
    { value: "99", label: "99 – Outras saídas" },
];
