-- Enable UUID extension if not enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Sales Documents (Headers)
CREATE TABLE IF NOT EXISTS public.sales_documents (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    company_id UUID NOT NULL REFERENCES public.companies(id),
    doc_type TEXT NOT NULL CHECK (doc_type IN ('proposal', 'order')),
    document_number BIGINT GENERATED BY DEFAULT AS IDENTITY, -- Simple auto-increment per table (not per company, simplified for MVP)
    
    client_id UUID NOT NULL REFERENCES public.organizations(id),
    sales_rep_id UUID REFERENCES auth.users(id),
    price_table_id UUID, -- References price_tables(id) if exists
    payment_terms_id UUID, -- References payment_terms(id) if exists

    date_issued DATE NOT NULL DEFAULT CURRENT_DATE,
    valid_until DATE,
    delivery_date DATE,

    status_commercial TEXT NOT NULL DEFAULT 'draft' CHECK (status_commercial IN ('draft', 'sent', 'approved', 'confirmed', 'cancelled', 'lost')),
    status_logistic TEXT NOT NULL DEFAULT 'pending' CHECK (status_logistic IN ('pending', 'separation', 'expedition', 'delivered')),
    status_fiscal TEXT NOT NULL DEFAULT 'none' CHECK (status_fiscal IN ('none', 'authorized', 'cancelled', 'error')),

    is_antecipada BOOLEAN DEFAULT FALSE,

    subtotal_amount NUMERIC(15,2) DEFAULT 0,
    discount_amount NUMERIC(15,2) DEFAULT 0,
    freight_amount NUMERIC(15,2) DEFAULT 0,
    total_amount NUMERIC(15,2) DEFAULT 0,

    delivery_address_json JSONB,
    carrier_id UUID REFERENCES public.organizations(id), -- Carrier organization

    internal_notes TEXT,
    client_notes TEXT,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    deleted_at TIMESTAMP WITH TIME ZONE
);

-- Index for filtering
CREATE INDEX IF NOT EXISTS idx_sales_docs_company ON public.sales_documents(company_id);
CREATE INDEX IF NOT EXISTS idx_sales_docs_client ON public.sales_documents(client_id);
CREATE INDEX IF NOT EXISTS idx_sales_docs_status_comm ON public.sales_documents(status_commercial);

-- RLS
ALTER TABLE public.sales_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view sales docs of their company" ON public.sales_documents
    FOR SELECT USING (company_id IN (
        SELECT company_id FROM public.users WHERE id = auth.uid()
    ));

CREATE POLICY "Users can insert sales docs for their company" ON public.sales_documents
    FOR INSERT WITH CHECK (company_id IN (
        SELECT company_id FROM public.users WHERE id = auth.uid()
    ));

CREATE POLICY "Users can update sales docs of their company" ON public.sales_documents
    FOR UPDATE USING (company_id IN (
        SELECT company_id FROM public.users WHERE id = auth.uid()
    ));

-- 2. Sales Document Items
CREATE TABLE IF NOT EXISTS public.sales_document_items (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, -- Denormalized for RLS/Perf
    document_id UUID NOT NULL REFERENCES public.sales_documents(id) ON DELETE CASCADE,
    
    item_id UUID NOT NULL REFERENCES public.items(id), -- Product/Service
    
    quantity NUMERIC(15,4) NOT NULL,
    unit_price NUMERIC(15,2) NOT NULL,
    discount_amount NUMERIC(15,2) DEFAULT 0,
    total_amount NUMERIC(15,2) GENERATED ALWAYS AS ((quantity * unit_price) - discount_amount) STORED,

    notes TEXT,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sales_items_doc ON public.sales_document_items(document_id);

ALTER TABLE public.sales_document_items ENABLE ROW LEVEL SECURITY;

-- Simple RLS: rely on document_id check? Or join check. 
-- For performance/simplicity in MVP, we can assume if you can edit the document, you can edit items.
-- But strict RLS requires checking company via document.
CREATE POLICY "Users can manage items of their company docs" ON public.sales_document_items
    FOR ALL USING (
        document_id IN (
            SELECT id FROM public.sales_documents WHERE company_id IN (
                SELECT company_id FROM public.users WHERE id = auth.uid()
            )
        )
    );

-- 3. Sales Payments (Installments)
CREATE TABLE IF NOT EXISTS public.sales_document_payments (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    document_id UUID NOT NULL REFERENCES public.sales_documents(id) ON DELETE CASCADE,

    installment_number INTEGER NOT NULL,
    due_date DATE NOT NULL,
    amount NUMERIC(15,2) NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'discounted')),
    
    notes TEXT,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sales_payments_doc ON public.sales_document_payments(document_id);
ALTER TABLE public.sales_document_payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage payments of their company docs" ON public.sales_document_payments
    FOR ALL USING (
        document_id IN (
            SELECT id FROM public.sales_documents WHERE company_id IN (
                SELECT company_id FROM public.users WHERE id = auth.uid()
            )
        )
    );

-- 4. Sales Document NFes
CREATE TABLE IF NOT EXISTS public.sales_document_nfes (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    document_id UUID NOT NULL REFERENCES public.sales_documents(id) ON DELETE CASCADE,

    nfe_number BIGINT,
    nfe_series INTEGER,
    nfe_key TEXT,
    
    status TEXT NOT NULL CHECK (status IN ('authorized', 'cancelled', 'processing', 'error')),
    issued_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    is_antecipada BOOLEAN DEFAULT FALSE,
    details TEXT,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sales_nfes_doc ON public.sales_document_nfes(document_id);
ALTER TABLE public.sales_document_nfes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage nfes of their company docs" ON public.sales_document_nfes
    FOR ALL USING (
        document_id IN (
            SELECT id FROM public.sales_documents WHERE company_id IN (
                SELECT company_id FROM public.users WHERE id = auth.uid()
            )
        )
    );

-- 5. Sales History (Audit Log)
CREATE TABLE IF NOT EXISTS public.sales_document_history (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    document_id UUID NOT NULL REFERENCES public.sales_documents(id) ON DELETE CASCADE,
    
    user_id UUID REFERENCES auth.users(id),
    
    event_type TEXT NOT NULL, -- 'created', 'updated', 'status_change', 'nfe_issued'
    description TEXT NOT NULL,
    metadata JSONB, -- Previous values, etc.

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sales_history_doc ON public.sales_document_history(document_id);
ALTER TABLE public.sales_document_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view history of their company docs" ON public.sales_document_history
    FOR SELECT USING (
        document_id IN (
            SELECT id FROM public.sales_documents WHERE company_id IN (
                SELECT company_id FROM public.users WHERE id = auth.uid()
            )
        )
    );
