-- Financeiro > Desconto de Duplicatas (Factor)
-- Core schema, enums, RLS and audit-ready structures

BEGIN;

-- ---------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'factor_operation_status_en') THEN
        CREATE TYPE public.factor_operation_status_en AS ENUM (
            'draft',
            'sent_to_factor',
            'in_adjustment',
            'completed',
            'cancelled'
        );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'factor_item_action_en') THEN
        CREATE TYPE public.factor_item_action_en AS ENUM (
            'discount',
            'buyback',
            'due_date_change'
        );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'factor_response_status_en') THEN
        CREATE TYPE public.factor_response_status_en AS ENUM (
            'pending',
            'accepted',
            'rejected',
            'adjusted'
        );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'factor_attachment_type_en') THEN
        CREATE TYPE public.factor_attachment_type_en AS ENUM (
            'package_csv',
            'package_zip',
            'package_report',
            'return_import',
            'user_upload'
        );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'factor_posting_type_en') THEN
        CREATE TYPE public.factor_posting_type_en AS ENUM (
            'ar_discount_settlement',
            'ap_factor_cost',
            'ap_buyback',
            'ap_buyback_settlement'
        );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'factor_custody_status_en') THEN
        CREATE TYPE public.factor_custody_status_en AS ENUM (
            'own',
            'with_factor',
            'repurchased'
        );
    END IF;
END $$;

-- ---------------------------------------------------------------------
-- Master: Factors
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.factors (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    organization_id UUID REFERENCES public.organizations(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    code TEXT,
    default_interest_rate NUMERIC(8, 4) NOT NULL DEFAULT 0 CHECK (default_interest_rate >= 0),
    default_fee_rate NUMERIC(8, 4) NOT NULL DEFAULT 0 CHECK (default_fee_rate >= 0),
    default_iof_rate NUMERIC(8, 4) NOT NULL DEFAULT 0 CHECK (default_iof_rate >= 0),
    default_other_cost_rate NUMERIC(8, 4) NOT NULL DEFAULT 0 CHECK (default_other_cost_rate >= 0),
    default_grace_days INTEGER NOT NULL DEFAULT 0 CHECK (default_grace_days >= 0),
    default_auto_settle_buyback BOOLEAN NOT NULL DEFAULT false,
    is_active BOOLEAN NOT NULL DEFAULT true,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID REFERENCES auth.users(id),
    UNIQUE(company_id, name)
);

CREATE INDEX IF NOT EXISTS idx_factors_company_active ON public.factors(company_id, is_active);
CREATE INDEX IF NOT EXISTS idx_factors_org ON public.factors(organization_id);

-- ---------------------------------------------------------------------
-- Operation headers
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.factor_operations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    factor_id UUID NOT NULL REFERENCES public.factors(id) ON DELETE RESTRICT,
    operation_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
    reference TEXT,
    issue_date DATE NOT NULL DEFAULT CURRENT_DATE,
    expected_settlement_date DATE,
    settlement_account_id UUID REFERENCES public.company_bank_accounts(id),
    status public.factor_operation_status_en NOT NULL DEFAULT 'draft',
    gross_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    costs_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    net_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    version_counter INTEGER NOT NULL DEFAULT 0 CHECK (version_counter >= 0),
    sent_at TIMESTAMPTZ,
    sent_by UUID REFERENCES auth.users(id),
    last_response_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    completed_by UUID REFERENCES auth.users(id),
    cancelled_at TIMESTAMPTZ,
    cancelled_by UUID REFERENCES auth.users(id),
    cancel_reason TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID REFERENCES auth.users(id),
    UNIQUE(company_id, operation_number)
);

CREATE INDEX IF NOT EXISTS idx_factor_operations_company_status ON public.factor_operations(company_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_factor_operations_factor ON public.factor_operations(factor_id);

-- ---------------------------------------------------------------------
-- Operation items (working set)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.factor_operation_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    operation_id UUID NOT NULL REFERENCES public.factor_operations(id) ON DELETE CASCADE,
    line_no INTEGER NOT NULL CHECK (line_no > 0),
    action_type public.factor_item_action_en NOT NULL,
    ar_installment_id UUID NOT NULL REFERENCES public.ar_installments(id) ON DELETE RESTRICT,
    ar_title_id UUID NOT NULL REFERENCES public.ar_titles(id) ON DELETE RESTRICT,
    sales_document_id UUID REFERENCES public.sales_documents(id) ON DELETE SET NULL,
    customer_id UUID REFERENCES public.organizations(id) ON DELETE SET NULL,
    installment_number_snapshot INTEGER NOT NULL CHECK (installment_number_snapshot > 0),
    due_date_snapshot DATE NOT NULL,
    amount_snapshot NUMERIC(15, 2) NOT NULL CHECK (amount_snapshot > 0),
    proposed_due_date DATE,
    buyback_settle_now BOOLEAN NOT NULL DEFAULT false,
    status public.factor_response_status_en NOT NULL DEFAULT 'pending',
    final_amount NUMERIC(15, 2),
    final_due_date DATE,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID REFERENCES auth.users(id),
    UNIQUE(operation_id, line_no),
    UNIQUE(operation_id, ar_installment_id, action_type),
    CONSTRAINT factor_item_due_date_change_requires_new_due
        CHECK (action_type <> 'due_date_change' OR proposed_due_date IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_factor_items_operation ON public.factor_operation_items(operation_id, line_no);
CREATE INDEX IF NOT EXISTS idx_factor_items_installment ON public.factor_operation_items(ar_installment_id);
CREATE INDEX IF NOT EXISTS idx_factor_items_status ON public.factor_operation_items(status);

-- ---------------------------------------------------------------------
-- Package versions (snapshot V1, V2...)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.factor_operation_versions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    operation_id UUID NOT NULL REFERENCES public.factor_operations(id) ON DELETE CASCADE,
    version_number INTEGER NOT NULL CHECK (version_number > 0),
    source_status public.factor_operation_status_en NOT NULL,
    total_items INTEGER NOT NULL DEFAULT 0,
    gross_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    costs_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    net_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    snapshot_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    package_csv_path TEXT,
    package_zip_path TEXT,
    package_report_path TEXT,
    sent_at TIMESTAMPTZ,
    sent_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID REFERENCES auth.users(id),
    UNIQUE(operation_id, version_number)
);

CREATE INDEX IF NOT EXISTS idx_factor_versions_operation ON public.factor_operation_versions(operation_id, version_number DESC);

-- current version pointer
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'factor_operations'
          AND column_name = 'current_version_id'
    ) THEN
        ALTER TABLE public.factor_operations
            ADD COLUMN current_version_id UUID REFERENCES public.factor_operation_versions(id) ON DELETE SET NULL;
    END IF;
END $$;

-- ---------------------------------------------------------------------
-- Return from factor (per item)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.factor_operation_responses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    operation_id UUID NOT NULL REFERENCES public.factor_operations(id) ON DELETE CASCADE,
    version_id UUID NOT NULL REFERENCES public.factor_operation_versions(id) ON DELETE CASCADE,
    operation_item_id UUID NOT NULL REFERENCES public.factor_operation_items(id) ON DELETE CASCADE,
    response_status public.factor_response_status_en NOT NULL DEFAULT 'pending',
    response_code TEXT,
    response_message TEXT,
    accepted_amount NUMERIC(15, 2),
    adjusted_amount NUMERIC(15, 2),
    adjusted_due_date DATE,
    fee_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    interest_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    iof_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    other_cost_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    total_cost_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(version_id, operation_item_id)
);

CREATE INDEX IF NOT EXISTS idx_factor_responses_operation ON public.factor_operation_responses(operation_id, version_id);
CREATE INDEX IF NOT EXISTS idx_factor_responses_status ON public.factor_operation_responses(response_status);

-- ---------------------------------------------------------------------
-- Attachments
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.factor_operation_attachments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    operation_id UUID NOT NULL REFERENCES public.factor_operations(id) ON DELETE CASCADE,
    version_id UUID REFERENCES public.factor_operation_versions(id) ON DELETE SET NULL,
    attachment_type public.factor_attachment_type_en NOT NULL,
    file_name TEXT NOT NULL,
    mime_type TEXT NOT NULL,
    file_size BIGINT CHECK (file_size IS NULL OR file_size >= 0),
    storage_path TEXT NOT NULL,
    uploaded_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_factor_attachments_operation ON public.factor_operation_attachments(operation_id, created_at DESC);

-- ---------------------------------------------------------------------
-- Generated postings for traceability + idempotency
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.factor_operation_postings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    operation_id UUID NOT NULL REFERENCES public.factor_operations(id) ON DELETE CASCADE,
    posting_type public.factor_posting_type_en NOT NULL,
    posting_key TEXT NOT NULL,
    ar_title_id UUID REFERENCES public.ar_titles(id) ON DELETE SET NULL,
    ap_title_id UUID REFERENCES public.ap_titles(id) ON DELETE SET NULL,
    ar_payment_id UUID REFERENCES public.ar_payments(id) ON DELETE SET NULL,
    ap_payment_id UUID REFERENCES public.ap_payments(id) ON DELETE SET NULL,
    settlement_id UUID REFERENCES public.financial_settlements(id) ON DELETE SET NULL,
    amount NUMERIC(15, 2) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID REFERENCES auth.users(id),
    UNIQUE(operation_id, posting_key)
);

CREATE INDEX IF NOT EXISTS idx_factor_postings_operation ON public.factor_operation_postings(operation_id);

-- ---------------------------------------------------------------------
-- AR installments custody fields
-- ---------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'ar_installments' AND column_name = 'factor_custody_status'
    ) THEN
        ALTER TABLE public.ar_installments
            ADD COLUMN factor_custody_status public.factor_custody_status_en NOT NULL DEFAULT 'own';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'ar_installments' AND column_name = 'factor_id'
    ) THEN
        ALTER TABLE public.ar_installments
            ADD COLUMN factor_id UUID REFERENCES public.factors(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'ar_installments' AND column_name = 'factor_operation_item_id'
    ) THEN
        ALTER TABLE public.ar_installments
            ADD COLUMN factor_operation_item_id UUID REFERENCES public.factor_operation_items(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'ar_installments' AND column_name = 'factor_assigned_at'
    ) THEN
        ALTER TABLE public.ar_installments
            ADD COLUMN factor_assigned_at TIMESTAMPTZ;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'ar_installments' AND column_name = 'factor_released_at'
    ) THEN
        ALTER TABLE public.ar_installments
            ADD COLUMN factor_released_at TIMESTAMPTZ;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_ar_installments_factor_custody ON public.ar_installments(company_id, factor_custody_status, status);

-- ---------------------------------------------------------------------
-- Updated-at trigger (reusable)
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_updated_at_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_factor_updated_at_factors ON public.factors;
CREATE TRIGGER trg_factor_updated_at_factors
BEFORE UPDATE ON public.factors
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_timestamp();

DROP TRIGGER IF EXISTS trg_factor_updated_at_operations ON public.factor_operations;
CREATE TRIGGER trg_factor_updated_at_operations
BEFORE UPDATE ON public.factor_operations
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_timestamp();

DROP TRIGGER IF EXISTS trg_factor_updated_at_items ON public.factor_operation_items;
CREATE TRIGGER trg_factor_updated_at_items
BEFORE UPDATE ON public.factor_operation_items
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_timestamp();

DROP TRIGGER IF EXISTS trg_factor_updated_at_responses ON public.factor_operation_responses;
CREATE TRIGGER trg_factor_updated_at_responses
BEFORE UPDATE ON public.factor_operation_responses
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_timestamp();

-- ---------------------------------------------------------------------
-- Company consistency guards
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.ensure_factor_operation_company_consistency()
RETURNS TRIGGER AS $$
DECLARE
    v_factor_company UUID;
BEGIN
    SELECT company_id INTO v_factor_company FROM public.factors WHERE id = NEW.factor_id;

    IF v_factor_company IS NULL THEN
        RAISE EXCEPTION 'Factor % not found', NEW.factor_id;
    END IF;

    IF v_factor_company <> NEW.company_id THEN
        RAISE EXCEPTION 'Factor company mismatch';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_factor_operation_company_guard ON public.factor_operations;
CREATE TRIGGER trg_factor_operation_company_guard
BEFORE INSERT OR UPDATE ON public.factor_operations
FOR EACH ROW EXECUTE FUNCTION public.ensure_factor_operation_company_consistency();

CREATE OR REPLACE FUNCTION public.ensure_factor_item_company_consistency()
RETURNS TRIGGER AS $$
DECLARE
    v_operation_company UUID;
    v_installment_company UUID;
BEGIN
    SELECT company_id INTO v_operation_company FROM public.factor_operations WHERE id = NEW.operation_id;
    SELECT company_id INTO v_installment_company FROM public.ar_installments WHERE id = NEW.ar_installment_id;

    IF v_operation_company IS NULL OR v_installment_company IS NULL THEN
        RAISE EXCEPTION 'Operation or installment not found';
    END IF;

    IF NEW.company_id <> v_operation_company OR NEW.company_id <> v_installment_company THEN
        RAISE EXCEPTION 'Factor item company mismatch';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_factor_item_company_guard ON public.factor_operation_items;
CREATE TRIGGER trg_factor_item_company_guard
BEFORE INSERT OR UPDATE ON public.factor_operation_items
FOR EACH ROW EXECUTE FUNCTION public.ensure_factor_item_company_consistency();

CREATE OR REPLACE FUNCTION public.ensure_factor_child_company_consistency()
RETURNS TRIGGER AS $$
DECLARE
    v_operation_company UUID;
BEGIN
    SELECT company_id INTO v_operation_company FROM public.factor_operations WHERE id = NEW.operation_id;

    IF v_operation_company IS NULL THEN
        RAISE EXCEPTION 'Operation % not found', NEW.operation_id;
    END IF;

    IF NEW.company_id <> v_operation_company THEN
        RAISE EXCEPTION 'Child company mismatch';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_factor_versions_company_guard ON public.factor_operation_versions;
CREATE TRIGGER trg_factor_versions_company_guard
BEFORE INSERT OR UPDATE ON public.factor_operation_versions
FOR EACH ROW EXECUTE FUNCTION public.ensure_factor_child_company_consistency();

DROP TRIGGER IF EXISTS trg_factor_responses_company_guard ON public.factor_operation_responses;
CREATE TRIGGER trg_factor_responses_company_guard
BEFORE INSERT OR UPDATE ON public.factor_operation_responses
FOR EACH ROW EXECUTE FUNCTION public.ensure_factor_child_company_consistency();

DROP TRIGGER IF EXISTS trg_factor_attachments_company_guard ON public.factor_operation_attachments;
CREATE TRIGGER trg_factor_attachments_company_guard
BEFORE INSERT OR UPDATE ON public.factor_operation_attachments
FOR EACH ROW EXECUTE FUNCTION public.ensure_factor_child_company_consistency();

DROP TRIGGER IF EXISTS trg_factor_postings_company_guard ON public.factor_operation_postings;
CREATE TRIGGER trg_factor_postings_company_guard
BEFORE INSERT OR UPDATE ON public.factor_operation_postings
FOR EACH ROW EXECUTE FUNCTION public.ensure_factor_child_company_consistency();

-- ---------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------
ALTER TABLE public.factors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.factor_operations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.factor_operation_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.factor_operation_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.factor_operation_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.factor_operation_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.factor_operation_postings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS factors_tenant_access ON public.factors;
CREATE POLICY factors_tenant_access
ON public.factors
FOR ALL TO authenticated
USING (public.is_member_of(company_id))
WITH CHECK (public.is_member_of(company_id));

DROP POLICY IF EXISTS factor_operations_tenant_access ON public.factor_operations;
CREATE POLICY factor_operations_tenant_access
ON public.factor_operations
FOR ALL TO authenticated
USING (public.is_member_of(company_id))
WITH CHECK (public.is_member_of(company_id));

DROP POLICY IF EXISTS factor_operation_items_tenant_access ON public.factor_operation_items;
CREATE POLICY factor_operation_items_tenant_access
ON public.factor_operation_items
FOR ALL TO authenticated
USING (public.is_member_of(company_id))
WITH CHECK (public.is_member_of(company_id));

DROP POLICY IF EXISTS factor_operation_versions_tenant_access ON public.factor_operation_versions;
CREATE POLICY factor_operation_versions_tenant_access
ON public.factor_operation_versions
FOR ALL TO authenticated
USING (public.is_member_of(company_id))
WITH CHECK (public.is_member_of(company_id));

DROP POLICY IF EXISTS factor_operation_responses_tenant_access ON public.factor_operation_responses;
CREATE POLICY factor_operation_responses_tenant_access
ON public.factor_operation_responses
FOR ALL TO authenticated
USING (public.is_member_of(company_id))
WITH CHECK (public.is_member_of(company_id));

DROP POLICY IF EXISTS factor_operation_attachments_tenant_access ON public.factor_operation_attachments;
CREATE POLICY factor_operation_attachments_tenant_access
ON public.factor_operation_attachments
FOR ALL TO authenticated
USING (public.is_member_of(company_id))
WITH CHECK (public.is_member_of(company_id));

DROP POLICY IF EXISTS factor_operation_postings_tenant_access ON public.factor_operation_postings;
CREATE POLICY factor_operation_postings_tenant_access
ON public.factor_operation_postings
FOR ALL TO authenticated
USING (public.is_member_of(company_id))
WITH CHECK (public.is_member_of(company_id));

-- ---------------------------------------------------------------------
-- Comments
-- ---------------------------------------------------------------------
COMMENT ON TABLE public.factors IS 'Cadastro de instituições de fomento (factor) por empresa';
COMMENT ON TABLE public.factor_operations IS 'Operações de desconto de duplicatas com fluxo completo';
COMMENT ON TABLE public.factor_operation_items IS 'Itens da operação: desconto, recompra e alteração de vencimento';
COMMENT ON TABLE public.factor_operation_versions IS 'Snapshots de pacote enviados à factor (V1, V2, ...)';
COMMENT ON TABLE public.factor_operation_responses IS 'Retorno da factor por item de operação';
COMMENT ON TABLE public.factor_operation_attachments IS 'Metadados de artefatos e anexos da operação';
COMMENT ON TABLE public.factor_operation_postings IS 'Rastreabilidade/idempotência dos lançamentos gerados na conclusão';

COMMIT;
