
-- Migration: Force Schema Cache Reload
-- Description: Updates column comment to ensure schema cache detects changes and notifies PostgREST.

COMMENT ON COLUMN public.sales_documents.total_weight_kg IS 'Calculated net weight (kg) - Autogenerated';
COMMENT ON COLUMN public.sales_documents.total_gross_weight_kg IS 'Calculated gross weight (kg) - Autogenerated';

NOTIFY pgrst, 'reload schema';
