// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(app)/configuracoes/preferencias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracoes/preferencias">> = Specific
  const handler = {} as typeof import("../../../app/(app)/configuracoes/preferencias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/cadastros/condicoes-de-pagamento/nova/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/cadastros/condicoes-de-pagamento/nova">> = Specific
  const handler = {} as typeof import("../../../app/app/cadastros/condicoes-de-pagamento/nova/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/cadastros/condicoes-de-pagamento/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/cadastros/condicoes-de-pagamento">> = Specific
  const handler = {} as typeof import("../../../app/app/cadastros/condicoes-de-pagamento/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/cadastros/grupos-tributarios/novo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/cadastros/grupos-tributarios/novo">> = Specific
  const handler = {} as typeof import("../../../app/app/cadastros/grupos-tributarios/novo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/cadastros/grupos-tributarios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/cadastros/grupos-tributarios">> = Specific
  const handler = {} as typeof import("../../../app/app/cadastros/grupos-tributarios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/cadastros/pessoas-e-empresas/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/cadastros/pessoas-e-empresas/[id]">> = Specific
  const handler = {} as typeof import("../../../app/app/cadastros/pessoas-e-empresas/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/cadastros/pessoas-e-empresas/novo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/cadastros/pessoas-e-empresas/novo">> = Specific
  const handler = {} as typeof import("../../../app/app/cadastros/pessoas-e-empresas/novo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/cadastros/pessoas-e-empresas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/cadastros/pessoas-e-empresas">> = Specific
  const handler = {} as typeof import("../../../app/app/cadastros/pessoas-e-empresas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/cadastros/produtos/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/cadastros/produtos/[id]">> = Specific
  const handler = {} as typeof import("../../../app/app/cadastros/produtos/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/cadastros/produtos/novo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/cadastros/produtos/novo">> = Specific
  const handler = {} as typeof import("../../../app/app/cadastros/produtos/novo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/cadastros/produtos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/cadastros/produtos">> = Specific
  const handler = {} as typeof import("../../../app/app/cadastros/produtos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/cadastros/tabelas-de-preco/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/cadastros/tabelas-de-preco/[id]">> = Specific
  const handler = {} as typeof import("../../../app/app/cadastros/tabelas-de-preco/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/cadastros/tabelas-de-preco/nova/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/cadastros/tabelas-de-preco/nova">> = Specific
  const handler = {} as typeof import("../../../app/app/cadastros/tabelas-de-preco/nova/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/cadastros/tabelas-de-preco/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/cadastros/tabelas-de-preco">> = Specific
  const handler = {} as typeof import("../../../app/app/cadastros/tabelas-de-preco/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/clients/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/clients/[id]">> = Specific
  const handler = {} as typeof import("../../../app/app/clients/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/clients/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/clients/new">> = Specific
  const handler = {} as typeof import("../../../app/app/clients/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/clients">> = Specific
  const handler = {} as typeof import("../../../app/app/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/compras/pedidos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/compras/pedidos">> = Specific
  const handler = {} as typeof import("../../../app/app/compras/pedidos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/compras/recebimento/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/compras/recebimento">> = Specific
  const handler = {} as typeof import("../../../app/app/compras/recebimento/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/configuracoes/cadastros-basicos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/configuracoes/cadastros-basicos">> = Specific
  const handler = {} as typeof import("../../../app/app/configuracoes/cadastros-basicos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/configuracoes/conta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/configuracoes/conta">> = Specific
  const handler = {} as typeof import("../../../app/app/configuracoes/conta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/configuracoes/empresa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/configuracoes/empresa">> = Specific
  const handler = {} as typeof import("../../../app/app/configuracoes/empresa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/configuracoes/preferencias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/configuracoes/preferencias">> = Specific
  const handler = {} as typeof import("../../../app/app/configuracoes/preferencias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/crm/[dealId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/crm/[dealId]">> = Specific
  const handler = {} as typeof import("../../../app/app/crm/[dealId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/crm/atividades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/crm/atividades">> = Specific
  const handler = {} as typeof import("../../../app/app/crm/atividades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/crm/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/crm/leads">> = Specific
  const handler = {} as typeof import("../../../app/app/crm/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/crm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/crm">> = Specific
  const handler = {} as typeof import("../../../app/app/crm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/crm/pipeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/crm/pipeline">> = Specific
  const handler = {} as typeof import("../../../app/app/crm/pipeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/estoque/inventario/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/estoque/inventario">> = Specific
  const handler = {} as typeof import("../../../app/app/estoque/inventario/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/estoque/movimentacoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/estoque/movimentacoes">> = Specific
  const handler = {} as typeof import("../../../app/app/estoque/movimentacoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/estoque/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/estoque">> = Specific
  const handler = {} as typeof import("../../../app/app/estoque/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/estoque/saldos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/estoque/saldos">> = Specific
  const handler = {} as typeof import("../../../app/app/estoque/saldos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/expedicao-separacao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/expedicao-separacao">> = Specific
  const handler = {} as typeof import("../../../app/app/expedicao-separacao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/expedicao/conferencia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/expedicao/conferencia">> = Specific
  const handler = {} as typeof import("../../../app/app/expedicao/conferencia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/expedicao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/expedicao">> = Specific
  const handler = {} as typeof import("../../../app/app/expedicao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/expedicao/romaneios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/expedicao/romaneios">> = Specific
  const handler = {} as typeof import("../../../app/app/expedicao/romaneios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/expedicao/separacao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/expedicao/separacao">> = Specific
  const handler = {} as typeof import("../../../app/app/expedicao/separacao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/financeiro/aprovacoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/financeiro/aprovacoes">> = Specific
  const handler = {} as typeof import("../../../app/app/financeiro/aprovacoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/financeiro/caixa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/financeiro/caixa">> = Specific
  const handler = {} as typeof import("../../../app/app/financeiro/caixa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/financeiro/dre/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/financeiro/dre">> = Specific
  const handler = {} as typeof import("../../../app/app/financeiro/dre/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/financeiro/fluxo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/financeiro/fluxo">> = Specific
  const handler = {} as typeof import("../../../app/app/financeiro/fluxo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/financeiro/pagar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/financeiro/pagar">> = Specific
  const handler = {} as typeof import("../../../app/app/financeiro/pagar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/financeiro/receber/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/financeiro/receber">> = Specific
  const handler = {} as typeof import("../../../app/app/financeiro/receber/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/fiscal/configuracoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/fiscal/configuracoes">> = Specific
  const handler = {} as typeof import("../../../app/app/fiscal/configuracoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/fiscal/nfe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/fiscal/nfe">> = Specific
  const handler = {} as typeof import("../../../app/app/fiscal/nfe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/fiscal/operacoes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/fiscal/operacoes/[id]">> = Specific
  const handler = {} as typeof import("../../../app/app/fiscal/operacoes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/fiscal/operacoes/novo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/fiscal/operacoes/novo">> = Specific
  const handler = {} as typeof import("../../../app/app/fiscal/operacoes/novo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/fiscal/operacoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/fiscal/operacoes">> = Specific
  const handler = {} as typeof import("../../../app/app/fiscal/operacoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/frota/veiculos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/frota/veiculos">> = Specific
  const handler = {} as typeof import("../../../app/app/frota/veiculos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/logistica/expedicao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/logistica/expedicao">> = Specific
  const handler = {} as typeof import("../../../app/app/logistica/expedicao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/logistica/historico/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/logistica/historico/[id]">> = Specific
  const handler = {} as typeof import("../../../app/app/logistica/historico/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/logistica/historico/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/logistica/historico">> = Specific
  const handler = {} as typeof import("../../../app/app/logistica/historico/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/logistica/retorno/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/logistica/retorno">> = Specific
  const handler = {} as typeof import("../../../app/app/logistica/retorno/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/logistica/rotas/conferencia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/logistica/rotas/conferencia">> = Specific
  const handler = {} as typeof import("../../../app/app/logistica/rotas/conferencia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/logistica/rotas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/logistica/rotas">> = Specific
  const handler = {} as typeof import("../../../app/app/logistica/rotas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/logistica/rotas/romaneios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/logistica/rotas/romaneios">> = Specific
  const handler = {} as typeof import("../../../app/app/logistica/rotas/romaneios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/logistica/rotas/separacao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/logistica/rotas/separacao">> = Specific
  const handler = {} as typeof import("../../../app/app/logistica/rotas/separacao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/new-company/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/new-company">> = Specific
  const handler = {} as typeof import("../../../app/app/new-company/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../../app/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/pcp/ordens/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/pcp/ordens">> = Specific
  const handler = {} as typeof import("../../../app/app/pcp/ordens/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/pcp/receitas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/pcp/receitas">> = Specific
  const handler = {} as typeof import("../../../app/app/pcp/receitas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/producao/apontamentos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/producao/apontamentos">> = Specific
  const handler = {} as typeof import("../../../app/app/producao/apontamentos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/producao/fichas-tecnicas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/producao/fichas-tecnicas">> = Specific
  const handler = {} as typeof import("../../../app/app/producao/fichas-tecnicas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/producao/ordens/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/producao/ordens">> = Specific
  const handler = {} as typeof import("../../../app/app/producao/ordens/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/rh/colaboradores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/rh/colaboradores">> = Specific
  const handler = {} as typeof import("../../../app/app/rh/colaboradores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/settings/company/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/settings/company">> = Specific
  const handler = {} as typeof import("../../../app/app/settings/company/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/settings/master-data/contact-tags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/settings/master-data/contact-tags">> = Specific
  const handler = {} as typeof import("../../../app/app/settings/master-data/contact-tags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/settings/master-data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/settings/master-data">> = Specific
  const handler = {} as typeof import("../../../app/app/settings/master-data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/settings/master-data/payment-terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/settings/master-data/payment-terms">> = Specific
  const handler = {} as typeof import("../../../app/app/settings/master-data/payment-terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/settings/master-data/person-types/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/settings/master-data/person-types">> = Specific
  const handler = {} as typeof import("../../../app/app/settings/master-data/person-types/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/vendas/orcamentos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/vendas/orcamentos">> = Specific
  const handler = {} as typeof import("../../../app/app/vendas/orcamentos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/vendas/pedidos/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/vendas/pedidos/[id]">> = Specific
  const handler = {} as typeof import("../../../app/app/vendas/pedidos/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/vendas/pedidos/novo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/vendas/pedidos/novo">> = Specific
  const handler = {} as typeof import("../../../app/app/vendas/pedidos/novo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/vendas/pedidos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/vendas/pedidos">> = Specific
  const handler = {} as typeof import("../../../app/app/vendas/pedidos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/vendas/relatorios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/vendas/relatorios">> = Specific
  const handler = {} as typeof import("../../../app/app/vendas/relatorios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/debug-routes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/debug-routes">> = Specific
  const handler = {} as typeof import("../../../app/debug-routes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../../app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cnpj/[cnpj]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cnpj/[cnpj]">> = Specific
  const handler = {} as typeof import("../../../app/api/cnpj/[cnpj]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/company/cert-a1/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/company/cert-a1/delete">> = Specific
  const handler = {} as typeof import("../../../app/api/company/cert-a1/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/company/cert-a1/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/company/cert-a1/password">> = Specific
  const handler = {} as typeof import("../../../app/api/company/cert-a1/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/company/cert-a1/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/company/cert-a1/upload">> = Specific
  const handler = {} as typeof import("../../../app/api/company/cert-a1/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/company/logo/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/company/logo/delete">> = Specific
  const handler = {} as typeof import("../../../app/api/company/logo/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/company/logo/signed-url/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/company/logo/signed-url">> = Specific
  const handler = {} as typeof import("../../../app/api/company/logo/signed-url/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/company/logo/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/company/logo/upload">> = Specific
  const handler = {} as typeof import("../../../app/api/company/logo/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/expedition/finish-return/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expedition/finish-return">> = Specific
  const handler = {} as typeof import("../../../app/api/expedition/finish-return/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/expedition/loading-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expedition/loading-check">> = Specific
  const handler = {} as typeof import("../../../app/api/expedition/loading-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/expedition/partial-load/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expedition/partial-load">> = Specific
  const handler = {} as typeof import("../../../app/api/expedition/partial-load/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/expedition/start-route/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expedition/start-route">> = Specific
  const handler = {} as typeof import("../../../app/api/expedition/start-route/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/finance/installments/[id]/pay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finance/installments/[id]/pay">> = Specific
  const handler = {} as typeof import("../../../app/api/finance/installments/[id]/pay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/finance/pay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finance/pay">> = Specific
  const handler = {} as typeof import("../../../app/api/finance/pay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/finance/postings/approve-batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finance/postings/approve-batch">> = Specific
  const handler = {} as typeof import("../../../app/api/finance/postings/approve-batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/finance/postings/hold-batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finance/postings/hold-batch">> = Specific
  const handler = {} as typeof import("../../../app/api/finance/postings/hold-batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/finance/postings/reject-batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finance/postings/reject-batch">> = Specific
  const handler = {} as typeof import("../../../app/api/finance/postings/reject-batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/finance/titles/[id]/installments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finance/titles/[id]/installments">> = Specific
  const handler = {} as typeof import("../../../app/api/finance/titles/[id]/installments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/finance/titles/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finance/titles/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/finance/titles/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory/purchase-in/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/purchase-in">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory/purchase-in/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/onboarding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding">> = Specific
  const handler = {} as typeof import("../../../app/api/onboarding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/orgs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orgs/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/orgs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/orgs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orgs">> = Specific
  const handler = {} as typeof import("../../../app/api/orgs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sales/approve-batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales/approve-batch">> = Specific
  const handler = {} as typeof import("../../../app/api/sales/approve-batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sales/delete-batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales/delete-batch">> = Specific
  const handler = {} as typeof import("../../../app/api/sales/delete-batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sales/orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales/orders/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/sales/orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sales/print-batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales/print-batch">> = Specific
  const handler = {} as typeof import("../../../app/api/sales/print-batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/work-orders/[id]/finish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/work-orders/[id]/finish">> = Specific
  const handler = {} as typeof import("../../../app/api/work-orders/[id]/finish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../../app/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
